[package]
name = "fun_visuals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
num = "0.4.0"
threadpool = "1.8.1"
num_cpus = "1.13.1"
